#! /bin/bash

if [ $USER != "root"  ]; then
	echo "You need root privileges"
	exit 1
fi


if [ "$1" = "up" ]; then
    	iptables -F
	iptables -P INPUT DROP
	iptables -A INPUT -p tcp --dport 22 -j ACCEPT
	iptables -A INPUT -p tcp --dport 10000 -j ACCEPT
	iptables -A INPUT -p udp --dport 5000:6000 -j ACCEPT
#	iptables -A INPUT -p tcp --dport 21 -j ACCEPT
	iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -A INPUT -i lo -s 127.0.0.1 -j ACCEPT
	iptables -A INPUT -i wlan0 -s 192.168.1.0/24 -j ACCEPT
	#disable ipv6
	ip6tables -F
	ip6tables -Z
	ip6tables -X
	ip6tables -P INPUT DROP ip6tables -P OUTPUT DROP ip6tables -P FORWARD DROP
    	echo "firewall up"
elif [ "$1" = "down" ]; then
	iptables -P INPUT ACCEPT
	iptables -F
	echo "firewall down"
elif [ "$1" = "add" ]; then
	iptables -A INPUT -s $2 -j ACCEPT
	echo "added" $2
	iptables -nL
elif [ "$1" = "savesail" ]; then
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "addons.mozilla." --algo kmp -j REJECT --reject-with tcp-reset
#	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "fbstatic" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "cdn." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "apis.google.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "fsdn." --algo kmp -j REJECT --reject-with tcp-reset
	#iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "youtube." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "ib.adnxs.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "clients.google." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "googleusercontent" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string ".cloudfront.net" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "trueconf" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "fonts.googleapis." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "maps.googleapis." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "google-analytics." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "api.solvemedia." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "analytics.yahoo." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "data.mozilla." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "ajax.googleapis." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "i.imgur.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "adnxs.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "ssl.fastly.net" --algo kmp -j REJECT --reject-with tcp-reset 
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "s0.wp.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "googleusercontent." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "s.m2pub.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "cf.ads.kontextua." --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "cdnjs.cloudflare.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "es-static0.infojobs." --algo kmp -j REJECT --reject-with tcp-reset 
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "adf.ly" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "gstatic.com" --algo kmp -j REJECT --reject-with tcp-reset
   	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "cloudfront.net" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "zotero.org" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "googleusercontent.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "gvt1.com" --algo kmp -j REJECT --reject-with tcp-reset
	iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "ping.chartbeat.net" --algo kmp -j REJECT --reject-with tcp-reset
	
	#~ iptables -A OUTPUT -d 10.0.0.1/32 -p tcp -m string --string "licdn." --algo kmp -j ACCEPT
elif [ "$1" = "apkstore" ];  then
	iptables -A INPUT -p tcp --dport 80 -j ACCEPT
else
	echo "choose a target"
fi
iptables -nL
