#! /bin/bash
NAME=$(echo $1 | cut -d _ -f 1)
declare -a ARCHS=("i386" "amd64")
mkdir -p ~/pbuilder/results/$NAME
ARCH=amd64 DIST=2015 pbuilder --build --allow-untrusted $1
ARCH=i386 DIST=2015 pbuilder --build --allow-untrusted $1
# Copiar desde tu result hasta la carpeta creada arriba
echo "Moviendo paquetes hacia el directorio de los debs"
mv ~/pbuilder/2015-${ARCHS[0]}/results/* ~/pbuilder/results/$NAME
mv ~/pbuilder/2015-${ARCHS[1]}/results/* ~/pbuilder/results/$NAME
