# Load plugins
source ~/.zsh_plugins.sh

source ~/dotfiles/zsh/env.zsh

source ~/dotfiles/zsh/options.zsh
source ~/dotfiles/zsh/functions/functions.zsh
source ~/dotfiles/zsh/functions/fzf-functions.zsh
source ~/dotfiles/zsh/functions/git-functions.zsh

source ~/dotfiles/bash_prompt/bash_aliases


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
